import { router } from 'expo-router';

/**
 * Thin wrapper over expo-router's imperative navigation. The KYB journey carries
 * its cross-screen state in the flow store (see `store/flow.ts`), so navigation
 * only needs the destination path. Typed routes are regenerated by the dev
 * server, so we accept a plain string here.
 */
export const go = (path: string) => router.push(path as never);
